name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests and generate JaCoCo report
      run: ./gradlew test jacocoTestReport

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: app/build/test-results/test

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: app/build/reports/tests/test

    - name: Upload JaCoCo report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: app/build/reports/jacoco/test

    # Add Docker build step
    - name: Build Docker image
      run: |
        docker build -t chethancn/3pchess:${{ github.sha }} .

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Tag and push Docker image
    - name: Tag Docker image
      run: |
        docker tag chethancn/3pchess:${{ github.sha }} chethancn/3pchess:latest

    - name: Push Docker image
      run: |
        docker push chethancn/3pchess:${{ github.sha }}
        docker push chethancn/3pchess:latest
