name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests and generate JaCoCo report
      run: ./gradlew test jacocoTestReport

    - name: Run PMD
      run: ./gradlew pmdMain

    - name: Upload PMD report
      uses: actions/upload-artifact@v4
      with:
        name: pmd-report
        path: app/build/reports/pmd

    - name: Upload JaCoCo report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: app/build/reports/jacoco/test
